=== martapastor/ABD-Practicas/xml/ejercicio06.dtd
<!--
Define una DTD que valide el documento XML para representar facturas.

Construye una DTD con las siguientes características:
        * El número de factura nfac, número de cliente ncli y número de pedido nped son valores únicos, por cada factura, cliente y pedido distintos. Son obligatorios.
        * Los números de teléfono y fax de la empresa no tienen por qué aparecer en la factura, pero siempre que lo hagan deberán tener los mismos valores (teléfono 917776688, fax 917776699).
        * La forma de pago puede tomar los valores: efectivo, tarjeta y plazos.
        * La moneda tiene que aparecer siempre, y siempre toma el valor euro.
        * El IVA tiene que aparecer siempre, y su valor no puede contener caracteres especiales. -->

<!-- Estilo general -->

<!ELEMENT factura (datos_empresa, datos_cliente, datos_factura)>

        <!ELEMENT datos_empresa (nombre,dir,poblacion,provincia,cif,telefono?,fax?)>
                <!ELEMENT nombre (#PCDATA)>
                <!ELEMENT dir (#PCDATA)>
                <!ELEMENT poblacion (#PCDATA)>
                <!ELEMENT provincia (#PCDATA)>
                <!ELEMENT cif (#PCDATA)>
                <!ELEMENT telefono EMPTY>
                <!ELEMENT fax EMPTY>

        <!ELEMENT datos_cliente (nombre, dir_env, poblacion, provincia)>
                <!-- <!ELEMENT nombre (#PCDATA)> -->
                <!ELEMENT dir_env (#PCDATA)>
                <!-- <!ELEMENT poblacion (#PCDATA)> -->
                <!-- <!ELEMENT provincia (#PCDATA)> -->

        <!ELEMENT datos_factura (fecha, linea*, base, cuota_iva, total)>
                <!ELEMENT fecha (#PCDATA)>
                <!ELEMENT linea (ref, desc, cant, precio, importe)>
                        <!ELEMENT ref (#PCDATA)>
                        <!ELEMENT desc (#PCDATA)>
                        <!ELEMENT cant (#PCDATA)>
                        <!ELEMENT precio (#PCDATA)>
                        <!ELEMENT importe (#PCDATA)>
                <!ELEMENT base (#PCDATA)>
                <!ELEMENT cuota_iva (#PCDATA)>
                <!ELEMENT total (#PCDATA)>


<!-- Restricciones -->

<!ATTLIST factura nfac ID #REQUIRED>
<!ATTLIST datos-cliente ncli ID #REQUIRED>
<!ATTLIST datos-factura nped ID #REQUIRED>

<!ELEMENT datos-empresa telefono (917776688)?>
<!ELEMENT datos-empresa fax (917776699)?>

<!ATTLIST datos-factura f-pago (efectivo | tarjeta | plazos)>

<!ATTLIST datos-factura moneda #FIXED "euro">

<!ATTLIST datos-factura iva #REQUIRED>

=== martapastor/ABD-Practicas/xml/dtd/factura.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE attributes SYSTEM "../ejercicio06.dtd">

<factura nfac="f999">
    <datos-empresa>
        <nombre>Equipos Digitales S.L.</nombre>
        <dir>Av. Valladolid</dir>
        <poblacion cod-postal="28043">Madrid</poblacion>
        <provincia>Madrid</provincia>
        <cif>Q-9876543</cif>
        <telefono/>
    </datos-empresa>

    <datos-cliente ncli="c879">
        <nombre>Dario Bueno Gutierrez</nombre>
        <dir-env>Av. Oporto, 7 - 4ºD</dir-env>
        <poblacion cod-postal="28043">Madrid</poblacion>
        <provincia>Madrid</provincia>
    </datos-cliente>

    <datos-factura nped="p731" iva="16" f-pago= "efectivo" moneda="euro">
        <fecha>12−01−2005</fecha>

        <linea>
            <ref>MII93000F/8</ref>
            <desc>MICRO PENTIUM IV 3000MHZ FB800</desc>
            <cant>1</cant>
            <precio>230</precio>
            <importe>266,80</importe>
        </linea>

        <linea>
            <ref>MB8QDIP4</ref>
            <desc>PLACA BASE QDI P4</desc>
            <cant>1</cant>
            <precio>180</precio>
            <importe>208,80</importe>
        </linea>

        <linea>
            <ref>MEDD512M32</ref>
            <desc>DIMM DDR 512MB 3200</desc>
            <cant>2</cant>
            <precio>40</precio>
            <importe>92,80</importe>
        </linea>

        <linea>
            <ref>HD250GSA7</ref>
            <desc>DISCO DURO 250GB S−ATA 7200</desc>
            <cant>4</cant>
            <precio>120</precio>
            <importe>556,80</importe>
        </linea>

        <base>970,00</base>
        <cuota-iva>155,20</cuota-iva>
        <total>1125,20</total>

    </datos-factura>
</factura>
