=== martapastor/ABD-Practicas/xml/dtd/contactos.dtd
<!ELEMENT agenda (contacto)+>
    <!ELEMENT contacto (nombre, apellidos, direccion?, telefono*)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT apellidos (#PCDATA)>
        <!ELEMENT direccion (calle, numero, codigo-postal, localidad >
            <!ELEMENT calle (#PCDATA)>
            <!ELEMENT numero (#PCDATA)>
            <!ELEMENT codigo-postal (#PCDATA)>
            <!ELEMENT localidad (#PCDATA)>
        <!ELEMENT telefono (#PCDATA)>

<!ATTLIST contacto dni CDATA #REQUIRED>
    <!ATTLIST telefono tipo (casa | trabajo | movil) #REQUIRED>

=== martapastor/ABD-Practicas/xml/dtd/contactos.xml
<?xml version="1.0" encoding="UTF−8"?>
<!DOCTYPE agenda SYSTEM "contactos.dtd">

<agenda>
    <contacto dni="51233412H">
        <nombre>David</nombre>
        <apellidos>Álvez Campos</apellidos>
        <direccion>
            <calle>Paseo de Ondarreta</calle>
            <numero>5</numero>
            <codigo-postal>20018</codigo-postal>
            <localidad>San Sebastián</localidad>
        </direccion>
        <telefono tipo="casa">943102321</telefono>
        <telefono tipo="movil">617702341</telefono>
    </contacto>

    <contacto dni="46821354T">
        <nombre>Víctor</nombre>
        <apellidos>Martín Moreno</apellidos>
        <telefono tipo="casa">914621100</telefono>
    </contacto>
</agenda>
